# Generated by Django 4.1.7 on 2023-02-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='users',
            new_name='user',
        ),
    ]
